kind: pipeline
name: default

volumes: # 定义主机的存储分卷
  - name: cache
    host:
      path: /tmp/cache
steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount: ["/drone/.gradle"]
  - name: gradle-assemble
    image: gradle
    commands:
      - GRADLE_USER_HOME=/drone/.gradle && gradle quarkusBuild --build-cache --parallel
  - name: docker
    image: plugins/docker
    settings:
      repo: docker-base.meizhuli.net:5020/mzl-board
      tags: latest
      registry: docker-base.meizhuli.net:5020
      insecure: true
      debug: false
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount: ["/drone/.gradle"]
  - name: publish
    image: appleboy/drone-ssh
    settings:
      host: mzl-nightly.ns.meizhuli.net
      username: root
      password:
        from_secret: server_password
      port: 22
      script:
        - cd /data/mzl-nightly
        - docker-compose pull && docker-compose down && docker-compose up -d
trigger:
  branch:
    - master
    - feature