kind: pipeline
name: default

volumes:
  - name: cache
    host:
      path: /tmp/cache
steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount: ["./gradle","./node_modules"]
  - name: webpack
    image: node
    commands:
      - cd views
      - npm install && npm run build
      - mv dist ../src/main/resources/META-INF/resources/app
  - name: build
    image: gradle:jdk14
    commands:
      - gradle quarkusBuild -g ./gradle --info --scan --build-cache --parallel -Dorg.gradle.jvmargs=-Xmx256m
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount: ["./gradle","./node_modules"]
  - name: docker
    image: plugins/docker
    settings:
      repo: docker-base.meizhuli.net:5020/mzl-board
      tags: latest
      registry: docker-base.meizhuli.net:5020
      insecure: true
      debug: false
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  - name: publish
    image: appleboy/drone-ssh
    settings:
      host: mzl-nightly.ns.meizhuli.net
      username: root
      password:
        from_secret: server_password
      port: 22
      script:
        - cd /data/mzl-nightly
        - docker-compose pull && docker-compose down && docker-compose up -d
trigger:
  branch:
    - master
    - feature