/**
 * this file is auto generated by TTO-CodeGenerator v1.3.10 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */

package net.fze.mzl.board.repo;

import io.quarkus.hibernate.orm.panache.PanacheRepository
import net.fze.mzl.board.pojo.CusFollowLogEntity
import javax.enterprise.context.ApplicationScoped

/** ¿Í»§»Ø·Ã¼ÇÂ¼仓储接口  */
@ApplicationScoped
class CusFollowLogJpaRepository : PanacheRepository<CusFollowLogEntity> {

}