/**
 * this file is auto generated by tto v1.3.11 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/fzen/tto
 *
 */
package net.fze.mzl.board.resources

import net.fze.mzl.board.pojo.FollowCusEntity
import net.fze.mzl.board.service.FollowCusService
import com.line.arch.commons.std.Result
import javax.inject.Inject
import javax.ws.rs.*
import javax.ws.rs.core.MediaType

/* »Ø·Ã¿Í»§±í资源 */
@Path("/follow_cus")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
class FollowCusResource {
    @Inject
    private lateinit var service:FollowCusService

    @GET
    @Path("/{id}")
    fun get(@PathParam("id") id:Int): FollowCusEntity? {
        return service.findByIdOrNull(id)
    }

    @GET
    fun list(): Set<FollowCusEntity> {
        return mutableSetOf()
    }

    @POST
    fun save(entity: FollowCusEntity):Result {
        val err = this.service.saveFollowCus(entity)
        if(err != null)return Result.create(1,err.message)
        return Result.OK
    }

    @DELETE
    @Path("/{id}")
    fun delete(@PathParam("id") id:Int):Result {
        val err = this.service.deleteById(id)
        if(err != null)return Result.create(1,err.message)
        return Result.OK
    }
}