/**
 * this file is auto generated by tto v1.3.11 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/fzen/tto
 *
 */
package net.fze.mzl.board.resources

import net.fze.mzl.board.pojo.LostShopTypeEntity
import net.fze.mzl.board.service.LostShopTypeService
import com.line.arch.commons.std.Result
import javax.inject.Inject
import javax.ws.rs.*
import javax.ws.rs.core.MediaType

/* 流失店铺类型表资源 */
@Path("/lost_shop_type")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
class LostShopTypeResource {
    @Inject
    private lateinit var service:LostShopTypeService

    @GET
    @Path("/{id}")
    fun get(@PathParam("id") id:Int): LostShopTypeEntity? {
        return service.findByIdOrNull(id)
    }

    @GET
    fun list(): Set<LostShopTypeEntity> {
        return mutableSetOf()
    }

    @POST
    fun save(entity: LostShopTypeEntity):Result {
        val err = this.service.saveLostShopType(entity)
        if(err != null)return Result.create(1,err.message)
        return Result.OK
    }

    @DELETE
    @Path("/{id}")
    fun delete(@PathParam("id") id:Int):Result {
        val err = this.service.deleteById(id)
        if(err != null)return Result.create(1,err.message)
        return Result.OK
    }
}