/**
 * this file is auto generated by tto v1.3.11 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/fzen/tto
 *
 */
package net.fze.mzl.board.resources

import net.fze.mzl.board.pojo.OutMoneyEntity
import net.fze.mzl.board.service.OutMoneyService
import com.line.arch.commons.std.Result
import javax.inject.Inject
import javax.ws.rs.*
import javax.ws.rs.core.MediaType

/* 提现表资源 */
@Path("/out_money")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
class OutMoneyResource {
    @Inject
    private lateinit var service:OutMoneyService

    @GET
    @Path("/{id}")
    fun get(@PathParam("id") id:Int): OutMoneyEntity? {
        return service.findByIdOrNull(id)
    }

    @GET
    fun list(): Set<OutMoneyEntity> {
        return mutableSetOf()
    }

    @POST
    fun save(entity: OutMoneyEntity):Result {
        val err = this.service.saveOutMoney(entity)
        if(err != null)return Result.create(1,err.message)
        return Result.OK
    }

    @DELETE
    @Path("/{id}")
    fun delete(@PathParam("id") id:Int):Result {
        val err = this.service.deleteById(id)
        if(err != null)return Result.create(1,err.message)
        return Result.OK
    }
}