/**
 * this file is auto generated by tto v1.3.11 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/fzen/tto
 *
 *//**
 * this file is auto generated by TTO-CodeGenerator v1.3.11 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */

package net.fze.mzl.board.service

import net.fze.mzl.board.pojo.DemandModEntity
import net.fze.mzl.board.repo.DemandModJpaRepository
import javax.inject.Inject
import javax.enterprise.inject.Default
import javax.enterprise.context.ApplicationScoped
import com.line.arch.commons.std.catch
import com.line.arch.commons.std.TypesConv

/** 需求模块表服务  */
@ApplicationScoped
class DemandModService {
    @Inject@field:Default
    lateinit var repo: DemandModJpaRepository

    fun parseId(id:Any):Long{return TypesConv.toLong(id)}

    // 根据ID查找需求模块表
    fun findByIdOrNull(id:Int):DemandModEntity?{
        return this.repo.findById(this.parseId(id))
    }

    // 保存需求模块表
    fun saveDemandMod(e: DemandModEntity):Error? {
        return catch {
            var dst: DemandModEntity
            if (e.id > 0) {
                dst = this.repo.findById(this.parseId(e.id))!!
            } else {
                dst = DemandModEntity()
            }

            dst.id = e.id
            dst.modName = e.modName
            this.repo.persist(dst)
            null
        }.error()
    }

    // 批量保存需求模块表
    fun saveAllDemandMod(entities:Iterable<DemandModEntity>){
        return this.repo.persist(entities)
    }

    // 删除需求模块表
    fun deleteById(id:Int):Error? {
        return catch {
            this.repo.deleteById(this.parseId(id))
        }.error()
    }

}
