/**
 * this file is auto generated by tto v1.3.11 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/fzen/tto
 *
 *//**
 * this file is auto generated by TTO-CodeGenerator v1.3.11 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */

package net.fze.mzl.board.service

import net.fze.mzl.board.pojo.FollowCusEntity
import net.fze.mzl.board.repo.FollowCusJpaRepository
import javax.inject.Inject
import javax.enterprise.inject.Default
import javax.enterprise.context.ApplicationScoped
import com.line.arch.commons.std.catch
import com.line.arch.commons.std.TypesConv

/** »Ø·Ã¿Í»§±í服务  */
@ApplicationScoped
class FollowCusService {
    @Inject@field:Default
    lateinit var repo: FollowCusJpaRepository

    fun parseId(id:Any):Long{return TypesConv.toLong(id)}

    // 根据ID查找»Ø·Ã¿Í»§±í
    fun findByIdOrNull(id:Int):FollowCusEntity?{
        return this.repo.findById(this.parseId(id))
    }

    // 保存»Ø·Ã¿Í»§±í
    fun saveFollowCus(e: FollowCusEntity):Error? {
        return catch {
            var dst: FollowCusEntity
            if (e.id > 0) {
                dst = this.repo.findById(this.parseId(e.id))!!
            } else {
                dst = FollowCusEntity()
            }

            dst.id = e.id
            dst.cusName = e.cusName
            dst.cusPhone = e.cusPhone
            dst.cusSource = e.cusSource
            dst.createdTime = e.createdTime
            dst.firstVisitTime = e.firstVisitTime
            dst.siteId = e.siteId
            dst.clientIp = e.clientIp
            dst.deviceOs = e.deviceOs
            dst.referer = e.referer
            dst.userFrom = e.userFrom
            dst.userDistrict = e.userDistrict
            dst.userPlace = e.userPlace
            this.repo.persist(dst)
            null
        }.error()
    }

    // 批量保存»Ø·Ã¿Í»§±í
    fun saveAllFollowCus(entities:Iterable<FollowCusEntity>){
        return this.repo.persist(entities)
    }

    // 删除»Ø·Ã¿Í»§±í
    fun deleteById(id:Int):Error? {
        return catch {
            this.repo.deleteById(this.parseId(id))
        }.error()
    }

}
