/**
 * this file is auto generated by tto v1.3.11 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/fzen/tto
 *
 *//**
 * this file is auto generated by TTO-CodeGenerator v1.3.11 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */

package net.fze.mzl.board.service

import net.fze.mzl.board.pojo.HelpMenuEntity
import net.fze.mzl.board.repo.HelpMenuJpaRepository
import javax.inject.Inject
import javax.enterprise.inject.Default
import javax.enterprise.context.ApplicationScoped
import com.line.arch.commons.std.catch
import com.line.arch.commons.std.TypesConv

/** 帮助中心菜单服务  */
@ApplicationScoped
class HelpMenuService {
    @Inject@field:Default
    lateinit var repo: HelpMenuJpaRepository

    fun parseId(id:Any):Long{return TypesConv.toLong(id)}

    // 根据ID查找帮助中心菜单
    fun findByIdOrNull(id:Int):HelpMenuEntity?{
        return this.repo.findById(this.parseId(id))
    }

    // 保存帮助中心菜单
    fun saveHelpMenu(e: HelpMenuEntity):Error? {
        return catch {
            var dst: HelpMenuEntity
            if (e.id > 0) {
                dst = this.repo.findById(this.parseId(e.id))!!
            } else {
                dst = HelpMenuEntity()
            }

            dst.id = e.id
            dst.parentId = e.parentId
            dst.name = e.name
            dst.perms = e.perms
            dst.type = e.type
            dst.icon = e.icon
            dst.locationCode = e.locationCode
            dst.sketch = e.sketch
            dst.description = e.description
            dst.video = e.video
            dst.orderNum = e.orderNum
            dst.createTime = e.createTime
            this.repo.persist(dst)
            null
        }.error()
    }

    // 批量保存帮助中心菜单
    fun saveAllHelpMenu(entities:Iterable<HelpMenuEntity>){
        return this.repo.persist(entities)
    }

    // 删除帮助中心菜单
    fun deleteById(id:Int):Error? {
        return catch {
            this.repo.deleteById(this.parseId(id))
        }.error()
    }

}
