/**
 * this file is auto generated by tto v1.3.11 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/fzen/tto
 *
 *//**
 * this file is auto generated by TTO-CodeGenerator v1.3.11 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */

package net.fze.mzl.board.service

import net.fze.mzl.board.pojo.LoadingSettingsEntity
import net.fze.mzl.board.repo.LoadingSettingsJpaRepository
import javax.inject.Inject
import javax.enterprise.inject.Default
import javax.enterprise.context.ApplicationScoped
import com.line.arch.commons.std.catch
import com.line.arch.commons.std.TypesConv

/** ¼ÓÔØÒ³ÉèÖÃ±í服务  */
@ApplicationScoped
class LoadingSettingsService {
    @Inject@field:Default
    lateinit var repo: LoadingSettingsJpaRepository

    fun parseId(id:Any):Long{return TypesConv.toLong(id)}

    // 根据ID查找¼ÓÔØÒ³ÉèÖÃ±í
    fun findByIdOrNull(id:Int):LoadingSettingsEntity?{
        return this.repo.findById(this.parseId(id))
    }

    // 保存¼ÓÔØÒ³ÉèÖÃ±í
    fun saveLoadingSettings(e: LoadingSettingsEntity):Error? {
        return catch {
            var dst: LoadingSettingsEntity
            if (e.id > 0) {
                dst = this.repo.findById(this.parseId(e.id))!!
            } else {
                dst = LoadingSettingsEntity()
            }

            dst.id = e.id
            dst.userName = e.userName
            dst.createdTime = e.createdTime
            dst.state = e.state
            dst.userCode = e.userCode
            dst.fileName = e.fileName
            dst.filePath = e.filePath
            this.repo.persist(dst)
            null
        }.error()
    }

    // 批量保存¼ÓÔØÒ³ÉèÖÃ±í
    fun saveAllLoadingSettings(entities:Iterable<LoadingSettingsEntity>){
        return this.repo.persist(entities)
    }

    // 删除¼ÓÔØÒ³ÉèÖÃ±í
    fun deleteById(id:Int):Error? {
        return catch {
            this.repo.deleteById(this.parseId(id))
        }.error()
    }

}
