/**
 * this file is auto generated by tto v1.3.11 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/fzen/tto
 *
 *//**
 * this file is auto generated by TTO-CodeGenerator v1.3.11 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */

package net.fze.mzl.board.service

import net.fze.mzl.board.pojo.LostShopLogEntity
import net.fze.mzl.board.repo.LostShopLogJpaRepository
import javax.inject.Inject
import javax.enterprise.inject.Default
import javax.enterprise.context.ApplicationScoped
import com.line.arch.commons.std.catch
import com.line.arch.commons.std.TypesConv

/** 流失店铺日志表服务  */
@ApplicationScoped
class LostShopLogService {
    @Inject@field:Default
    lateinit var repo: LostShopLogJpaRepository

    fun parseId(id:Any):Long{return TypesConv.toLong(id)}

    // 根据ID查找流失店铺日志表
    fun findByIdOrNull(id:Int):LostShopLogEntity?{
        return this.repo.findById(this.parseId(id))
    }

    // 保存流失店铺日志表
    fun saveLostShopLog(e: LostShopLogEntity):Error? {
        return catch {
            var dst: LostShopLogEntity
            if (e.id > 0) {
                dst = this.repo.findById(this.parseId(e.id))!!
            } else {
                dst = LostShopLogEntity()
            }

            dst.id = e.id
            dst.shopId = e.shopId
            dst.opId = e.opId
            dst.opName = e.opName
            dst.typeId = e.typeId
            dst.remark = e.remark
            dst.state = e.state
            dst.createTime = e.createTime
            this.repo.persist(dst)
            null
        }.error()
    }

    // 批量保存流失店铺日志表
    fun saveAllLostShopLog(entities:Iterable<LostShopLogEntity>){
        return this.repo.persist(entities)
    }

    // 删除流失店铺日志表
    fun deleteById(id:Int):Error? {
        return catch {
            this.repo.deleteById(this.parseId(id))
        }.error()
    }

}
