/**
 * this file is auto generated by tto v1.3.11 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/fzen/tto
 *
 *//**
 * this file is auto generated by TTO-CodeGenerator v1.3.11 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */

package net.fze.mzl.board.service

import net.fze.mzl.board.pojo.OutMoneyEntity
import net.fze.mzl.board.repo.OutMoneyJpaRepository
import javax.inject.Inject
import javax.enterprise.inject.Default
import javax.enterprise.context.ApplicationScoped
import com.line.arch.commons.std.catch
import com.line.arch.commons.std.TypesConv

/** 提现表服务  */
@ApplicationScoped
class OutMoneyService {
    @Inject@field:Default
    lateinit var repo: OutMoneyJpaRepository

    fun parseId(id:Any):Long{return TypesConv.toLong(id)}

    // 根据ID查找提现表
    fun findByIdOrNull(id:Int):OutMoneyEntity?{
        return this.repo.findById(this.parseId(id))
    }

    // 保存提现表
    fun saveOutMoney(e: OutMoneyEntity):Error? {
        return catch {
            var dst: OutMoneyEntity
            if (e.id > 0) {
                dst = this.repo.findById(this.parseId(e.id))!!
            } else {
                dst = OutMoneyEntity()
            }

            dst.id = e.id
            dst.outNum = e.outNum
            dst.thirdBill = e.thirdBill
            dst.poundage = e.poundage
            dst.feeRate = e.feeRate
            dst.checkMoney = e.checkMoney
            dst.state = e.state
            dst.operator = e.operator
            dst.opId = e.opId
            dst.outTime = e.outTime
            dst.createTime = e.createTime
            dst.updateTime = e.updateTime
            this.repo.persist(dst)
            null
        }.error()
    }

    // 批量保存提现表
    fun saveAllOutMoney(entities:Iterable<OutMoneyEntity>){
        return this.repo.persist(entities)
    }

    // 删除提现表
    fun deleteById(id:Int):Error? {
        return catch {
            this.repo.deleteById(this.parseId(id))
        }.error()
    }

}
