/**
 * this file is auto generated by TTO-CodeGenerator v1.3.10 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */

package net.fze.mzl.board.pojo;

import javax.persistence.Basic;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;

/** ¿Í»§»Ø·Ã¼ÇÂ¼ */
@Entity
@Table(name = "cus_follow_log", schema = "")
public class CusFollowLogEntity {

    private int id;
    public void setId(int id){
        this.id = id;
    }

    /** ÎïÀíÖ÷¼ü */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id" ,length = 11)
    public int getId() {
        return this.id;
    }

    private int created_time;
    public void setCreatedTime(int created_time){
        this.created_time = created_time;
    }

    /** ´´½¨Ê±¼ä */
    @Basic
    @Column(name = "created_time" ,length = 11)
    public int getCreatedTime() {
        return this.created_time;
    }

    private int cus_id;
    public void setCusId(int cus_id){
        this.cus_id = cus_id;
    }

    /** ¿Í»§ID */
    @Basic
    @Column(name = "cus_id" ,length = 11)
    public int getCusId() {
        return this.cus_id;
    }

    private int shop_type;
    public void setShopType(int shop_type){
        this.shop_type = shop_type;
    }

    /** µêÆÌÀàÐÍ */
    @Basic
    @Column(name = "shop_type" ,length = 11)
    public int getShopType() {
        return this.shop_type;
    }

    private int follow_state;
    public void setFollowState(int follow_state){
        this.follow_state = follow_state;
    }

    /** »Ø·Ã×´Ì¬ 0:Î´»Ø·Ã£¬1³õ´Î»Ø·Ã£¬ 2ÔÙ´Î»Ø·Ã */
    @Basic
    @Column(name = "follow_state" ,length = 2)
    public int getFollowState() {
        return this.follow_state;
    }

    private int employee_number;
    public void setEmployeeNumber(int employee_number){
        this.employee_number = employee_number;
    }

    /** Ô±¹¤ÊýÁ¿ 1:3ÈËÒÔÉÏ  2£º3-5   3£º6-10  4£º10+ */
    @Basic
    @Column(name = "employee_number" ,length = 11)
    public int getEmployeeNumber() {
        return this.employee_number;
    }

    private int installation_status;
    public void setInstallationStatus(int installation_status){
        this.installation_status = installation_status;
    }

    /** °²×°×´Ì¬ 0:Î´°²×° 1£ºÒÑ°²×° 2£º¹Ø±Õ */
    @Basic
    @Column(name = "installation_status" ,length = 2)
    public int getInstallationStatus() {
        return this.installation_status;
    }

    private int next_follow_time;
    public void setNextFollowTime(int next_follow_time){
        this.next_follow_time = next_follow_time;
    }

    /** ÏÂ´Î»Ø·ÃÊ±¼ä */
    @Basic
    @Column(name = "next_follow_time" ,length = 11)
    public int getNextFollowTime() {
        return this.next_follow_time;
    }

    private int demand_mod;
    public void setDemandMod(int demand_mod){
        this.demand_mod = demand_mod;
    }

    /**  */
    @Basic
    @Column(name = "demand_mod", nullable = true ,length = 11)
    public int getDemandMod() {
        return this.demand_mod;
    }

    private int purchase_intention;
    public void setPurchaseIntention(int purchase_intention){
        this.purchase_intention = purchase_intention;
    }

    /** ¹ºÂòÒâÏò   1: ¸ß  2£ºÖÐ  3£ºµÍ  0:Î´Öª */
    @Basic
    @Column(name = "purchase_intention" ,length = 2)
    public int getPurchaseIntention() {
        return this.purchase_intention;
    }

    private String renarks;
    public void setRenarks(String renarks){
        this.renarks = renarks;
    }

    /** ±¸×¢ */
    @Basic
    @Column(name = "renarks" ,length = 256)
    public String getRenarks() {
        return this.renarks;
    }

    private String customer_name;
    public void setCustomerName(String customer_name){
        this.customer_name = customer_name;
    }

    /** ¿Í·þÃû×Ö */
    @Basic
    @Column(name = "customer_name" ,length = 64)
    public String getCustomerName() {
        return this.customer_name;
    }

    private int customer_id;
    public void setCustomerId(int customer_id){
        this.customer_id = customer_id;
    }

    /** ¿Í·þID */
    @Basic
    @Column(name = "customer_id" ,length = 11)
    public int getCustomerId() {
        return this.customer_id;
    }

    /** 拷贝数据  */
    public CusFollowLogEntity copy(CusFollowLogEntity src){
        CusFollowLogEntity dst = new CusFollowLogEntity();

        dst.setId(src.getId());
        dst.setCreatedTime(src.getCreatedTime());
        dst.setCusId(src.getCusId());
        dst.setShopType(src.getShopType());
        dst.setFollowState(src.getFollowState());
        dst.setEmployeeNumber(src.getEmployeeNumber());
        dst.setInstallationStatus(src.getInstallationStatus());
        dst.setNextFollowTime(src.getNextFollowTime());
        dst.setDemandMod(src.getDemandMod());
        dst.setPurchaseIntention(src.getPurchaseIntention());
        dst.setRenarks(src.getRenarks());
        dst.setCustomerName(src.getCustomerName());
        dst.setCustomerId(src.getCustomerId());
        return dst;
    }
}
