/**
 * this file is auto generated by TTO-CodeGenerator v1.3.10 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */

package net.fze.mzl.board.pojo;

import javax.persistence.Basic;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;

/**  */
@Entity
@Table(name = "cus_source", schema = "")
public class CusSourceEntity {

    private int id;
    public void setId(int id){
        this.id = id;
    }

    /**  物理主键 */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id" ,length = 11)
    public int getId() {
        return this.id;
    }

    private String cus_source;
    public void setCusSource(String cus_source){
        this.cus_source = cus_source;
    }

    /**  */
    @Basic
    @Column(name = "cus_source" ,length = 64)
    public String getCusSource() {
        return this.cus_source;
    }

    private String code;
    public void setCode(String code){
        this.code = code;
    }

    /** 资源代码 */
    @Basic
    @Column(name = "code" ,length = 16)
    public String getCode() {
        return this.code;
    }

    /** 拷贝数据  */
    public CusSourceEntity copy(CusSourceEntity src){
        CusSourceEntity dst = new CusSourceEntity();

        dst.setId(src.getId());
        dst.setCusSource(src.getCusSource());
        dst.setCode(src.getCode());
        return dst;
    }
}
