/**
 * this file is auto generated by TTO-CodeGenerator v1.3.10 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */

package net.fze.mzl.board.pojo;

import javax.persistence.Basic;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;

/** 代理回访表 */
@Entity
@Table(name = "fb_agent_info", schema = "")
public class FbAgentInfoEntity {

    private int id;
    public void setId(int id){
        this.id = id;
    }

    /** 物理主键 */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id" ,length = 11)
    public int getId() {
        return this.id;
    }

    private String person_name;
    public void setPersonName(String person_name){
        this.person_name = person_name;
    }

    /** 客户名字 */
    @Basic
    @Column(name = "person_name" ,length = 32)
    public String getPersonName() {
        return this.person_name;
    }

    private String person_phone;
    public void setPersonPhone(String person_phone){
        this.person_phone = person_phone;
    }

    /** 客户手机号 */
    @Basic
    @Column(name = "person_phone" ,length = 15)
    public String getPersonPhone() {
        return this.person_phone;
    }

    private String request_area;
    public void setRequestArea(String request_area){
        this.request_area = request_area;
    }

    /** 代理区域 */
    @Basic
    @Column(name = "request_area" ,length = 40)
    public String getRequestArea() {
        return this.request_area;
    }

    private int first_call_time;
    public void setFirstCallTime(int first_call_time){
        this.first_call_time = first_call_time;
    }

    /** 首次回访时间 */
    @Basic
    @Column(name = "first_call_time" ,length = 11)
    public int getFirstCallTime() {
        return this.first_call_time;
    }

    private String client_ip;
    public void setClientIp(String client_ip){
        this.client_ip = client_ip;
    }

    /** ip地址 */
    @Basic
    @Column(name = "client_ip" ,length = 64)
    public String getClientIp() {
        return this.client_ip;
    }

    private String referer;
    public void setReferer(String referer){
        this.referer = referer;
    }

    /** 来源地址 */
    @Basic
    @Column(name = "referer" ,length = 120)
    public String getReferer() {
        return this.referer;
    }

    private String device_os;
    public void setDeviceOs(String device_os){
        this.device_os = device_os;
    }

    /** 客户设备 */
    @Basic
    @Column(name = "device_os" ,length = 64)
    public String getDeviceOs() {
        return this.device_os;
    }

    private String user_from;
    public void setUserFrom(String user_from){
        this.user_from = user_from;
    }

    /** 客户来源 */
    @Basic
    @Column(name = "user_from" ,length = 64)
    public String getUserFrom() {
        return this.user_from;
    }

    private String user_district;
    public void setUserDistrict(String user_district){
        this.user_district = user_district;
    }

    /** 区域 */
    @Basic
    @Column(name = "user_district" ,length = 64)
    public String getUserDistrict() {
        return this.user_district;
    }

    private String user_place;
    public void setUserPlace(String user_place){
        this.user_place = user_place;
    }

    /** 具体地址 */
    @Basic
    @Column(name = "user_place" ,length = 256)
    public String getUserPlace() {
        return this.user_place;
    }

    private String remark;
    public void setRemark(String remark){
        this.remark = remark;
    }

    /** 备注 */
    @Basic
    @Column(name = "remark" ,length = 120)
    public String getRemark() {
        return this.remark;
    }

    private int created_time;
    public void setCreatedTime(int created_time){
        this.created_time = created_time;
    }

    /** 创建时间 */
    @Basic
    @Column(name = "created_time" ,length = 11)
    public int getCreatedTime() {
        return this.created_time;
    }

    /** 拷贝数据  */
    public FbAgentInfoEntity copy(FbAgentInfoEntity src){
        FbAgentInfoEntity dst = new FbAgentInfoEntity();

        dst.setId(src.getId());
        dst.setPersonName(src.getPersonName());
        dst.setPersonPhone(src.getPersonPhone());
        dst.setRequestArea(src.getRequestArea());
        dst.setFirstCallTime(src.getFirstCallTime());
        dst.setClientIp(src.getClientIp());
        dst.setReferer(src.getReferer());
        dst.setDeviceOs(src.getDeviceOs());
        dst.setUserFrom(src.getUserFrom());
        dst.setUserDistrict(src.getUserDistrict());
        dst.setUserPlace(src.getUserPlace());
        dst.setRemark(src.getRemark());
        dst.setCreatedTime(src.getCreatedTime());
        return dst;
    }
}
