/**
 * this file is auto generated by tto v1.3.11 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/fzen/tto
 *
 *//**
 * this file is auto generated by TTO-CodeGenerator v1.3.11 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */

package net.fze.mzl.board.pojo;

import javax.persistence.Basic;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;

/** 帮助中心菜单 */
@Entity
@Table(name = "help_menu", schema = "")
public class HelpMenuEntity {

    private Long id;
    public void setId(Long id){
        this.id = id;
    }

    /**  */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id" ,length = 11)
    public Long getId() {
        return this.id;
    }

    private Long parent_id;
    public void setParentId(Long parent_id){
        this.parent_id = parent_id;
    }

    /** 父菜单ID，一级菜单为0 */
    @Basic
    @Column(name = "parent_id" ,length = 11)
    public Long getParentId() {
        return this.parent_id;
    }

    private String name;
    public void setName(String name){
        this.name = name;
    }

    /** 菜单名称 */
    @Basic
    @Column(name = "name", nullable = true ,length = 50)
    public String getName() {
        return this.name;
    }

    private Long perms;
    public void setPerms(Long perms){
        this.perms = perms;
    }

    /** 授权 */
    @Basic
    @Column(name = "perms" ,length = 11)
    public Long getPerms() {
        return this.perms;
    }

    private Long type;
    public void setType(Long type){
        this.type = type;
    }

    /** 类型   0：目录 1：菜单  */
    @Basic
    @Column(name = "type" ,length = 11)
    public Long getType() {
        return this.type;
    }

    private String icon;
    public void setIcon(String icon){
        this.icon = icon;
    }

    /** 菜单图标 */
    @Basic
    @Column(name = "icon" ,length = 50)
    public String getIcon() {
        return this.icon;
    }

    private String location_code;
    public void setLocationCode(String location_code){
        this.location_code = location_code;
    }

    /** 位置code */
    @Basic
    @Column(name = "location_code" ,length = 128)
    public String getLocationCode() {
        return this.location_code;
    }

    private String sketch;
    public void setSketch(String sketch){
        this.sketch = sketch;
    }

    /** 简述 */
    @Basic
    @Column(name = "sketch" ,length = 500)
    public String getSketch() {
        return this.sketch;
    }

    private String description;
    public void setDescription(String description){
        this.description = description;
    }

    /** 说明 */
    @Basic
    @Column(name = "description" ,length = -1)
    public String getDescription() {
        return this.description;
    }

    private String video;
    public void setVideo(String video){
        this.video = video;
    }

    /** 视频 */
    @Basic
    @Column(name = "video" ,length = 1000)
    public String getVideo() {
        return this.video;
    }

    private Long order_num;
    public void setOrderNum(Long order_num){
        this.order_num = order_num;
    }

    /** 排序 */
    @Basic
    @Column(name = "order_num" ,length = 11)
    public Long getOrderNum() {
        return this.order_num;
    }

    private Long create_time;
    public void setCreateTime(Long create_time){
        this.create_time = create_time;
    }

    /** 创建时间 */
    @Basic
    @Column(name = "create_time" ,length = 11)
    public Long getCreateTime() {
        return this.create_time;
    }

    /** 拷贝数据  */
    public HelpMenuEntity copy(HelpMenuEntity src){
        HelpMenuEntity dst = new HelpMenuEntity();

        dst.setId(src.getId());
        dst.setParentId(src.getParentId());
        dst.setName(src.getName());
        dst.setPerms(src.getPerms());
        dst.setType(src.getType());
        dst.setIcon(src.getIcon());
        dst.setLocationCode(src.getLocationCode());
        dst.setSketch(src.getSketch());
        dst.setDescription(src.getDescription());
        dst.setVideo(src.getVideo());
        dst.setOrderNum(src.getOrderNum());
        dst.setCreateTime(src.getCreateTime());
        return dst;
    }
}
