/**
 * this file is auto generated by TTO-CodeGenerator v1.3.10 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */

package net.fze.mzl.board.pojo;

import javax.persistence.Basic;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;

/** ¼ÓÔØÒ³ÉèÖÃ±í */
@Entity
@Table(name = "loading_settings", schema = "")
public class LoadingSettingsEntity {

    private int id;
    public void setId(int id){
        this.id = id;
    }

    /** ÎïÀíÖ÷¼ü */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id" ,length = 11)
    public int getId() {
        return this.id;
    }

    private String user_name;
    public void setUserName(String user_name){
        this.user_name = user_name;
    }

    /** ²Ù×÷ÈËÃû×Ö */
    @Basic
    @Column(name = "user_name" ,length = 36)
    public String getUserName() {
        return this.user_name;
    }

    private int created_time;
    public void setCreatedTime(int created_time){
        this.created_time = created_time;
    }

    /** ´´½¨Ê±¼ä */
    @Basic
    @Column(name = "created_time" ,length = 11)
    public int getCreatedTime() {
        return this.created_time;
    }

    private int state;
    public void setState(int state){
        this.state = state;
    }

    /** ×´Ì¬ */
    @Basic
    @Column(name = "state" ,length = 1)
    public int getState() {
        return this.state;
    }

    private String user_code;
    public void setUserCode(String user_code){
        this.user_code = user_code;
    }

    /** ´´½¨ÈËcode */
    @Basic
    @Column(name = "user_code" ,length = 64)
    public String getUserCode() {
        return this.user_code;
    }

    private String file_name;
    public void setFileName(String file_name){
        this.file_name = file_name;
    }

    /** ÎÄ¼þÃû */
    @Basic
    @Column(name = "file_name" ,length = 256)
    public String getFileName() {
        return this.file_name;
    }

    private String file_path;
    public void setFilePath(String file_path){
        this.file_path = file_path;
    }

    /** ÎÄ¼þÂ·¾¶ */
    @Basic
    @Column(name = "file_path" ,length = 256)
    public String getFilePath() {
        return this.file_path;
    }

    /** 拷贝数据  */
    public LoadingSettingsEntity copy(LoadingSettingsEntity src){
        LoadingSettingsEntity dst = new LoadingSettingsEntity();

        dst.setId(src.getId());
        dst.setUserName(src.getUserName());
        dst.setCreatedTime(src.getCreatedTime());
        dst.setState(src.getState());
        dst.setUserCode(src.getUserCode());
        dst.setFileName(src.getFileName());
        dst.setFilePath(src.getFilePath());
        return dst;
    }
}
