/**
 * this file is auto generated by tto v1.3.11 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/fzen/tto
 *
 *//**
 * this file is auto generated by TTO-CodeGenerator v1.3.11 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */

package net.fze.mzl.board.pojo;

import javax.persistence.Basic;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;

/** 流失店铺状态表 */
@Entity
@Table(name = "lost_shop_state", schema = "")
public class LostShopStateEntity {

    private Long id;
    public void setId(Long id){
        this.id = id;
    }

    /** 编号 */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id" ,length = 11)
    public Long getId() {
        return this.id;
    }

    private Long shop_id;
    public void setShopId(Long shop_id){
        this.shop_id = shop_id;
    }

    /** 商铺ID */
    @Basic
    @Column(name = "shop_id" ,length = 11)
    public Long getShopId() {
        return this.shop_id;
    }

    private Long state;
    public void setState(Long state){
        this.state = state;
    }

    /** 状态 */
    @Basic
    @Column(name = "state" ,length = 11)
    public Long getState() {
        return this.state;
    }

    private Long op_id;
    public void setOpId(Long op_id){
        this.op_id = op_id;
    }

    /** 操作人ID */
    @Basic
    @Column(name = "op_id" ,length = 11)
    public Long getOpId() {
        return this.op_id;
    }

    private String op_name;
    public void setOpName(String op_name){
        this.op_name = op_name;
    }

    /** 操作人姓名 */
    @Basic
    @Column(name = "op_name" ,length = 16)
    public String getOpName() {
        return this.op_name;
    }

    private Long create_time;
    public void setCreateTime(Long create_time){
        this.create_time = create_time;
    }

    /** 创建时间 */
    @Basic
    @Column(name = "create_time" ,length = 11)
    public Long getCreateTime() {
        return this.create_time;
    }

    /** 拷贝数据  */
    public LostShopStateEntity copy(LostShopStateEntity src){
        LostShopStateEntity dst = new LostShopStateEntity();

        dst.setId(src.getId());
        dst.setShopId(src.getShopId());
        dst.setState(src.getState());
        dst.setOpId(src.getOpId());
        dst.setOpName(src.getOpName());
        dst.setCreateTime(src.getCreateTime());
        return dst;
    }
}
