/**
 * this file is auto generated by TTO-CodeGenerator v1.3.10 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */

package net.fze.mzl.board.pojo;

import javax.persistence.Basic;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;

/** 流失店铺类型表 */
@Entity
@Table(name = "lost_shop_type", schema = "")
public class LostShopTypeEntity {

    private int id;
    public void setId(int id){
        this.id = id;
    }

    /** 编号 */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id" ,length = 11)
    public int getId() {
        return this.id;
    }

    private String type;
    public void setType(String type){
        this.type = type;
    }

    /** 流失类型 */
    @Basic
    @Column(name = "type" ,length = 64)
    public String getType() {
        return this.type;
    }

    /** 拷贝数据  */
    public LostShopTypeEntity copy(LostShopTypeEntity src){
        LostShopTypeEntity dst = new LostShopTypeEntity();

        dst.setId(src.getId());
        dst.setType(src.getType());
        return dst;
    }
}
