/**
 * this file is auto generated by TTO-CodeGenerator v1.3.10 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */

package net.fze.mzl.board.pojo;

import javax.persistence.Basic;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;

/** 消息推送表 */
@Entity
@Table(name = "push_notice", schema = "")
public class PushNoticeEntity {

    private int id;
    public void setId(int id){
        this.id = id;
    }

    /** ID */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id" ,length = 11)
    public int getId() {
        return this.id;
    }

    private String title;
    public void setTitle(String title){
        this.title = title;
    }

    /** 标题 */
    @Basic
    @Column(name = "title" ,length = 256)
    public String getTitle() {
        return this.title;
    }

    private String content;
    public void setContent(String content){
        this.content = content;
    }

    /** 内容 */
    @Basic
    @Column(name = "content" ,length = -1)
    public String getContent() {
        return this.content;
    }

    private int channel;
    public void setChannel(int channel){
        this.channel = channel;
    }

    /** 推送渠道 */
    @Basic
    @Column(name = "channel" ,length = 11)
    public int getChannel() {
        return this.channel;
    }

    private int bullet_screen;
    public void setBulletScreen(int bullet_screen){
        this.bullet_screen = bullet_screen;
    }

    /** 弹幕 */
    @Basic
    @Column(name = "bullet_screen" ,length = 11)
    public int getBulletScreen() {
        return this.bullet_screen;
    }

    private int state;
    public void setState(int state){
        this.state = state;
    }

    /** 状态 */
    @Basic
    @Column(name = "state" ,length = 11)
    public int getState() {
        return this.state;
    }

    private int opt_id;
    public void setOptId(int opt_id){
        this.opt_id = opt_id;
    }

    /** 操作人ID */
    @Basic
    @Column(name = "opt_id" ,length = 11)
    public int getOptId() {
        return this.opt_id;
    }

    private String opt_name;
    public void setOptName(String opt_name){
        this.opt_name = opt_name;
    }

    /** 操作人姓名 */
    @Basic
    @Column(name = "opt_name" ,length = 24)
    public String getOptName() {
        return this.opt_name;
    }

    private int begin_time;
    public void setBeginTime(int begin_time){
        this.begin_time = begin_time;
    }

    /** 开始时间 */
    @Basic
    @Column(name = "begin_time" ,length = 11)
    public int getBeginTime() {
        return this.begin_time;
    }

    private int over_time;
    public void setOverTime(int over_time){
        this.over_time = over_time;
    }

    /** 结束时间 */
    @Basic
    @Column(name = "over_time" ,length = 11)
    public int getOverTime() {
        return this.over_time;
    }

    private int create_time;
    public void setCreateTime(int create_time){
        this.create_time = create_time;
    }

    /** 创建时间 */
    @Basic
    @Column(name = "create_time" ,length = 11)
    public int getCreateTime() {
        return this.create_time;
    }

    private int update_time;
    public void setUpdateTime(int update_time){
        this.update_time = update_time;
    }

    /** 修改时间 */
    @Basic
    @Column(name = "update_time" ,length = 11)
    public int getUpdateTime() {
        return this.update_time;
    }

    /** 拷贝数据  */
    public PushNoticeEntity copy(PushNoticeEntity src){
        PushNoticeEntity dst = new PushNoticeEntity();

        dst.setId(src.getId());
        dst.setTitle(src.getTitle());
        dst.setContent(src.getContent());
        dst.setChannel(src.getChannel());
        dst.setBulletScreen(src.getBulletScreen());
        dst.setState(src.getState());
        dst.setOptId(src.getOptId());
        dst.setOptName(src.getOptName());
        dst.setBeginTime(src.getBeginTime());
        dst.setOverTime(src.getOverTime());
        dst.setCreateTime(src.getCreateTime());
        dst.setUpdateTime(src.getUpdateTime());
        return dst;
    }
}
