/**
 * this file is auto generated by tto v1.3.11 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/fzen/tto
 *
 *//**
 * this file is auto generated by TTO-CodeGenerator v1.3.11 !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */

package net.fze.mzl.board.pojo;

import javax.persistence.Basic;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;

/** 消息推送表 */
@Entity
@Table(name = "push_notice", schema = "")
public class PushNoticeEntity {

    private Long id;
    public void setId(Long id){
        this.id = id;
    }

    /** ID */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id" ,length = 11)
    public Long getId() {
        return this.id;
    }

    private String title;
    public void setTitle(String title){
        this.title = title;
    }

    /** 标题 */
    @Basic
    @Column(name = "title" ,length = 256)
    public String getTitle() {
        return this.title;
    }

    private String content;
    public void setContent(String content){
        this.content = content;
    }

    /** 内容 */
    @Basic
    @Column(name = "content" ,length = -1)
    public String getContent() {
        return this.content;
    }

    private Long channel;
    public void setChannel(Long channel){
        this.channel = channel;
    }

    /** 推送渠道 */
    @Basic
    @Column(name = "channel" ,length = 11)
    public Long getChannel() {
        return this.channel;
    }

    private Long bullet_screen;
    public void setBulletScreen(Long bullet_screen){
        this.bullet_screen = bullet_screen;
    }

    /** 弹幕 */
    @Basic
    @Column(name = "bullet_screen" ,length = 11)
    public Long getBulletScreen() {
        return this.bullet_screen;
    }

    private Long state;
    public void setState(Long state){
        this.state = state;
    }

    /** 状态 */
    @Basic
    @Column(name = "state" ,length = 11)
    public Long getState() {
        return this.state;
    }

    private Long opt_id;
    public void setOptId(Long opt_id){
        this.opt_id = opt_id;
    }

    /** 操作人ID */
    @Basic
    @Column(name = "opt_id" ,length = 11)
    public Long getOptId() {
        return this.opt_id;
    }

    private String opt_name;
    public void setOptName(String opt_name){
        this.opt_name = opt_name;
    }

    /** 操作人姓名 */
    @Basic
    @Column(name = "opt_name" ,length = 24)
    public String getOptName() {
        return this.opt_name;
    }

    private Long begin_time;
    public void setBeginTime(Long begin_time){
        this.begin_time = begin_time;
    }

    /** 开始时间 */
    @Basic
    @Column(name = "begin_time" ,length = 11)
    public Long getBeginTime() {
        return this.begin_time;
    }

    private Long over_time;
    public void setOverTime(Long over_time){
        this.over_time = over_time;
    }

    /** 结束时间 */
    @Basic
    @Column(name = "over_time" ,length = 11)
    public Long getOverTime() {
        return this.over_time;
    }

    private Long create_time;
    public void setCreateTime(Long create_time){
        this.create_time = create_time;
    }

    /** 创建时间 */
    @Basic
    @Column(name = "create_time" ,length = 11)
    public Long getCreateTime() {
        return this.create_time;
    }

    private Long update_time;
    public void setUpdateTime(Long update_time){
        this.update_time = update_time;
    }

    /** 修改时间 */
    @Basic
    @Column(name = "update_time" ,length = 11)
    public Long getUpdateTime() {
        return this.update_time;
    }

    /** 拷贝数据  */
    public PushNoticeEntity copy(PushNoticeEntity src){
        PushNoticeEntity dst = new PushNoticeEntity();

        dst.setId(src.getId());
        dst.setTitle(src.getTitle());
        dst.setContent(src.getContent());
        dst.setChannel(src.getChannel());
        dst.setBulletScreen(src.getBulletScreen());
        dst.setState(src.getState());
        dst.setOptId(src.getOptId());
        dst.setOptName(src.getOptName());
        dst.setBeginTime(src.getBeginTime());
        dst.setOverTime(src.getOverTime());
        dst.setCreateTime(src.getCreateTime());
        dst.setUpdateTime(src.getUpdateTime());
        return dst;
    }
}
